# 旧
#spring:
#  profiles:
#    active: dev
#    include: devDB, devMVC

# 新
spring:
  profiles:
    active: @profile.active@
    group:
      "dev": devDB, devMVC
      "pro": proDB, proMVC
      "test": testDB, TestMVC