logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug

spring:
  application:
    name: rabbitmq-springboot
  rabbitmq:
    host: 47.76.68.216
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
    connection-timeout: 1s  # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true  # 开启超时重试机制
        multiplier: 5 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制【不建议开启】

