spring:
  profiles: common

tencent:
  cloud:
    appId: 腾讯云APPID
    secretId: 腾讯云SecretId
    secretKey: 腾讯云SecretKey
    region-public: 公有存储桶所在地域
    bucket-public: 公有存储桶名称
    region-private: 私有存储桶所在地域
    bucket-private: 私有存储桶名称
    face:
      groupName: hxds
      region: ap-beijing
  # 位置服务文档：https://lbs.qq.com/service/webService/webServiceGuide/route/webServiceMatrix
  # 腾讯地图坐标拾取：https://lbs.qq.com/getPoint
  map:
    key: U2ZBZ-7AJ63-2HT3O-RXI2S-JXMEE-Z2BY3

wx:
  app-id: 你的微信小程序APPID
  app-secret: 你的微信小程序密钥
  mch-id: 商户号（课程QQ群共享文件中获取）
  key: 商户密钥（课程QQ群共享文件中获取）
  cert-path: 商户数字证书文件路径（课程QQ群共享文件中获取）


