spring:
  application:
    name: rabbitmq-springboot
  rabbitmq:
    host: 47.76.68.216
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
