# 配置数据信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.76.68.216:3306/mybatis_plus?rewriteBatchedStatements=true
    username: root
    password: P@ssw0rd123!