server:
  port: 1000

spring:
  data:
    redis:
      host: 172.31.0.2  # yc服务器内网IP
      port: 5379
      database: 0
      password: yc
  cloud:
    nacos:
      discovery:
        server-addr: 172.31.0.2:18848
    gateway:
      discovery:
        locator:
          enabled: true   # 动态路由，从注册中心根据微服务的名称获得目标节点的地址
      routes: # 配置路由规则（数组/list）
        - id: authRoute   # 每一项路由规则都有一个唯一的id编号，可以自定义
          uri: lb://auth-service    # lb=负载均衡，会动态寻址
          predicates:
            - Path=/a/**,/passport/**
        - id: fileRoute
          uri: lb://file-service
          predicates:
            - Path=/f/**,/file/**,/static/**,/speech/**
        - id: mainRoute
          uri: lb://main-service
          predicates:
            - Path=/m/**,/userinfo/**,/friendRequest/**,/friendship/**,/friendCircle/**,/comment/**,/chat/**
      globalcors:  # 跨域配置
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
