server:
  servlet:
    context-path: /mis-bff
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # 不限制请求体大小

spring:
  application:
    name: mis-bff-service
  profiles: # dev-开发环境; prod-生产环境; test-测试环境;
    active: dev
#    active: test
#    active: prod

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 300000

# swagger在线文档配置
springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

